/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/frame/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/frame/AppLayout.vue')['default']
    BottomSheet: typeof import('./src/components/modal/BottomSheet.vue')['default']
    PatientAutocomplete: typeof import('./src/components/popup/PatientAutocomplete.vue')['default']
    ReservationPopup: typeof import('./src/components/popup/ReservationPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreatmentContentSelector: typeof import('./src/components/popup/TreatmentContentSelector.vue')['default']
    TreatmentItemSettingPopup: typeof import('./src/components/popup/TreatmentItemSettingPopup.vue')['default']
    UiDateNavigator: typeof import('./src/components/ui/UiDateNavigator.vue')['default']
    UiDoctorFilter: typeof import('./src/components/ui/UiDoctorFilter.vue')['default']
    UiMemberTypeToggle: typeof import('./src/components/ui/UiMemberTypeToggle.vue')['default']
    UiSearchInput: typeof import('./src/components/ui/UiSearchInput.vue')['default']
    UiSegmentedControl: typeof import('./src/components/ui/UiSegmentedControl.vue')['default']
    UiStatusFilter: typeof import('./src/components/ui/UiStatusFilter.vue')['default']
    UiSwitchButton: typeof import('./src/components/ui/UiSwitchButton.vue')['default']
    UiTimeSelect: typeof import('./src/components/ui/UiTimeSelect.vue')['default']
  }
}
